step component
subquery/subql-ui-components pull request #31
Opened 2022-11-23 05:07 UTC by bighammerw

##screenshot for parameters
<img width="1187" alt="Screen Shot 2022-11-23 at 5 22 06 PM" src="https://user-images.githubusercontent.com/92004774/203472454-d600f670-6308-4239-b381-d4fd72d579f2.png">
##screenshot for figma
<img width="1190" alt="Screen Shot 2022-11-23 at 5 23 01 PM" src="https://user-images.githubusercontent.com/92004774/203472486-4e3bccd2-3ede-4a80-a195-5132b3012d12.png">

2022-11-23 21:02 UTC, CaiYiLiang requested changes

2022-11-23 21:02 UTC, CaiYiLiang commented on components/common/modal/Modal.tsx
> +  const [current, setCurrent] = React.useState<number>(0);
accept `currentStep` as parameter for Modal component

2022-11-23 21:09 UTC, bighammerw commented on components/common/modal/Modal.tsx
> +  description?: string[] | React.ReactNode[];
In order to save the content with the step switch

2022-11-27 22:51 UTC, CaiYiLiang approved these changes

2022-11-27 22:52 UTC, merged